plugin.identity.keycloak:
  keycloakIssuerUrl: ${KEYCLOAK_ISSUER_URL}                  # https://id.reunico.com/realms/reunico.com
  keycloakAdminUrl: ${KEYCLOAK_ADMIN_URL}                    # https://id.reunico.com/admin/realms/reunico.com
  clientId: ${CAMUNDA_IDENTITY_CLIENT_ID}                    # camunda-identity-service
  clientSecret: ${CAMUNDA_IDENTITY_CLIENT_SECRET}
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: ${CAMUNDA_ADMIN_GROUP_NAME:-DevOps}
  disableSSLCertificateValidation: ${CAMUNDA_DISABLE_SSL_CERT_VALIDATION:false}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CAMUNDA_IDENTITY_CLIENT_ID}         # camunda-identity-service
            client-secret: ${CAMUNDA_IDENTITY_CLIENT_SECRET}
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URL}               # https://id.reunico.com/realms/reunico.com
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}               # https://.../protocol/openid-connect/certs