server:
  servlet:
    context-path: ${CAMUNDA_CONTEXT_PATH}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${CAMUNDA_DATASOURCE_URL}
    username: ${CAMUNDA_DATASOURCE_USERNAME}
    password: ${CAMUNDA_DATASOURCE_PASSWORD}
camunda.bpm:
  admin-user:
    id: ${CAMUNDA_LOGIN}
    password: ${CAMUNDA_PASSWORD}